sudo: required

language: c

services:
  - docker

matrix:
  include:
    # FAIL Cannot compile some dependencies
    #- env: IMG=quid2/eta CMD="etlas update;etlas build;etlas test :spec"
    # FAIL: incorr
    # No setup information found for ghcjs-8.6.0.1_ghc-8.6.2 on your platform.
    # This probably means a GHC bindist has not yet been added for OS key 'source'.
    # Supported versions: ghcjs-0.1.0.20150924_ghc-7.10.2
    #- env: IMG=quid2/x64-ubuntu-ghcjs CMD="stack test --stack-yaml stack-ghcjs.yaml"
    # FAIl compiling doctest-0.11.4
    #- env: IMG=quid2/x64-ubuntu-ghcjs-9.21 CMD="stack test --stack-yaml stack-ghcjs-9.21.yaml"
    # cabal OK
    # - env: IMG=quid2/x32-ubuntu-cabal CMD="cabal v2-update;cabal v2-build --only-dependencies --enable-tests;cabal v2-build;cabal v2-test"
    # ghc 7.10.3 OK
    # - env: IMG=quid2/x64-ubuntu-stack-lts-6.35 CMD="stack test --resolver lts-6.35"
    # ghc 8.0.2 OK
    # - env: IMG=quid2/x64-ubuntu-stack-lts-9.21 CMD="stack test --resolver lts-9.21"
    # ghc 8.2.2 OK
    # - env: IMG=quid2/x64-ubuntu-stack-lts-11.22 CMD="stack test --resolver lts-11.22"
    # ghc 8.4.4 OK
    # - env: IMG=quid2/x64-ubuntu-stack-lts-12.26 CMD="stack test --resolver lts-12.26"
    # ghc 8.6.5 OK
    # - env: IMG=quid2/x64-ubuntu-stack-lts-14.22 CMD="stack test --resolver lts-14.7"
    # ghc 8.8.2 (OK, with some changes to tests)
    # - env: IMG=quid2/x64-ubuntu-stack-nightly-2020-01-25 CMD="stack test --resolver nightly-2020-01-25"

before_install:
  - PKG=${PWD##*/}
  - docker pull $IMG

script:
  - docker run -it $IMG bash -c "git clone https://github.com/Quid2/$PKG;cd $PKG;$CMD"
