resolver: lts-14.27

packages:
  - .
#  - ../EXTERNAL/doctest

allow-newer: true

extra-deps:
  # Required for lts-6.35 and lts-9.21
  - quickcheck-instances-0.3.21
  - splitmix-0.0.2
  - time-compat-0.1.9.2.1

  # Modified doctest, used to generate static tests
  - git: https://github.com/tittoassini/doctest
    commit: c9cdbe4eee086cb8aa46e96532160320dd367f09
