resolver: lts-14.27

packages:
  - .
#  - ../EXTERNAL/doctest

allow-newer: true

extra-deps:
  - quickcheck-instances-0.3.22

  # Modified doctest, used to generate static tests
  - git: https://github.com/tittoassini/doctest
    commit: 5bded2c2ea4435e340ba727de9496e4c38a3e5ee
