resolver: lts-14.27

packages:
  - .
#  - ../EXTERNAL/doctest

allow-newer: true

extra-deps:
  # Required for lts-
  - quickcheck-instances-0.3.21
  - splitmix-0.0.2@sha256:e1c4d1202757d63cd4b4498d5fa600a792f2a315d2fdc6cf772f4679113c1819

  # Modified doctest, used to generate static tests
  - git: https://github.com/tittoassini/doctest
    commit: c9cdbe4eee086cb8aa46e96532160320dd367f09
