resolver: lts-14.27

packages:
  - .
#  - ../EXTERNAL/doctest

# Modified doctest, used to generate static tests
extra-deps:
  - git: https://github.com/tittoassini/doctest
    commit: 5bded2c2ea4435e340ba727de9496e4c38a3e5ee
