resolver: lts-14.27

packages:
  - .
#  - ../EXTERNAL/doctest

allow-newer: true

extra-deps:
  - quickcheck-instances-0.3.20

  # Modified doctest, used to generate static tests
  - git: https://github.com/tittoassini/doctest
    commit: c9cdbe4eee086cb8aa46e96532160320dd367f09
