resolver: lts-14.27

packages:
  - .
#  - ../EXTERNAL/doctest

allow-newer: true

extra-deps:
  # Required for lts-6.35 and lts-9.21
  - quickcheck-instances-0.3.22
  # - QuickCheck-2.13.2
  # - splitmix-0.0.2
  # - time-compat-1.9.3
  # - hashable-1.2.5.0
  #- semigroups-0.19.1

  # Modified doctest, used to generate static tests
  - git: https://github.com/tittoassini/doctest
    commit: c9cdbe4eee086cb8aa46e96532160320dd367f09
